import os
from typing import Any, Dict

from app.core.logger import logger
from app.services.github.strategies.base import GitHubEventStrategy
from app.services.notifications.discord import DiscordNotification
from app.services.github_client import GitHubClient
from app.services.ai.factory import get_ai_provider
from app.core.settings import settings


class PullRequestStrategy(GitHubEventStrategy):
    """Handles GitHub Pull Request events."""
    
    def __init__(self):
        self.discord = DiscordNotification()
        self.github_client = GitHubClient()
        
    async def execute(self, payload: Dict[str, Any]) -> None:
        action = payload.get("action", "unknown action")
        pr = payload.get("pull_request", {})
        number = pr.get("number", "unknown")
        title = pr.get("title", "No Title")
        pr_url = pr.get("html_url", "")
        author = pr.get("user", {}).get("login", "Unknown user")
        repo_name = payload.get("repository", {}).get("full_name", "Unknown Repo")
        repo_owner = payload.get("repository", {}).get("owner", {}).get("login", "Unknown")
        repo_short = payload.get("repository", {}).get("name", "Unknown")
        
        logger.info(f"Processing PULL_REQUEST event: PR #{number} was {action}: {title}")
        
        # Configure color based on action
        color = 3447003 # Blue for open
        original_action = action
        if action == "closed":
            color = 15158332 if pr.get("merged") else 10038562 # Purple merged, Red closed
            if pr.get("merged"):
                action = "merged"

        role_id = os.getenv("DISCORD_ROLE_ID")
        # Execute the Template Method
        await self.discord.send_notification(
            title=f"🔀 Pull Request {action.capitalize()}",
            message = f"<@&{role_id}>\n**[{repo_name}]** PR #{number}: {title}\nAction by: {author}",
            metadata={
                "color": color,
                "author": author,
                "url": pr_url
            }
        )
        
        # --- AI CODE REVIEW PIPELINE ---
        
        # Proceed with AI Code Review only for open, sync, reopen
        if original_action not in ["opened", "synchronize", "reopened"]:
            return
            
        logger.info(f"Starting AI Code Review for PR #{number}")
        
        try:
            files = await self.github_client.get_pr_files(repo_owner, repo_short, number)
            
            ai_provider = get_ai_provider()
            provider_name = settings.AI_PROVIDER
            model_name = settings.AI_MODEL or "default"
            if model_name == "default":
                defaults = {
                    "anthropic": "claude-3-5-sonnet-20241022",
                    "openai": "gpt-4o",
                    "gemini": "gemini-1.5-pro",
                    "groq": "llama-3.1-70b-versatile",
                    "ollama": "codellama"
                }
                model_name = defaults.get(provider_name, "default-model")
            
            reviews = []
            issues_found = 0
            
            for f in files:
                if f.status in ["removed", "unchanged"] or not f.patch:
                    continue
                    
                context = {
                    "repo": repo_name,
                    "title": title,
                    "filename": f.filename
                }
                
                review_comment = await ai_provider.review_code(f.patch, context)
                if review_comment:
                    reviews.append(f"### File: `{f.filename}`\n{review_comment}")
                    issues_found += 1
                    
            if not reviews:
                logger.info("No actionable feedback generated by AI. Skipping GitHub comment.")
                return
                
            summary = f"## 🤖 AI Code Review Summary\n\nReviewed by **{provider_name.capitalize()}** (`{model_name}`).\n\n"
            full_review = summary + "\n\n".join(reviews)
            
            # Post review to GitHub
            await self.github_client.post_pr_review(repo_owner, repo_short, number, full_review)
            
            # Send Notification to Discord via the existing Discord Notification Bot Service Template
            await self.discord.send_notification(
                title=f"🤖 AI Code Review Completed: PR #{number}",
                message=f"**Provider:** {provider_name.capitalize()} | **Model:** {model_name}\n"
                        f"**Issues Found:** {issues_found}\n\n"
                        f"Review posted on GitHub successfully.",
                metadata={
                    "color": 3447003, # Blue
                    "author": author,
                    "url": pr_url
                }
            )
            
        except Exception as e:
            logger.error(f"Error during AI Code Review pipeline: {str(e)}", exc_info=True)
